### ISSUE TITLE
license clarification

### ISSUE THREAD

**Issue by spatialtrail** [yunjunz/PySAR#3]
Hi, I am a little confused - I see this has a MIT license  but then I read it is only for non-commercial applications:
https://github.com/yunjunz/PySAR/blob/master/docs/Manual-1.2.0_201708.pdf

?

Thanks

**Comment by yunjunz** [comment]
I have changed the license to GNU GPL3 and update the manual accordingly. Commercial applications are allowed with NO liability nor warranty.
