### ISSUE TITLE
refactor pysarApp to use pysar as modules instead of using subprocess

### ISSUE THREAD

**Issue by yunjunz** [yunjunz/PySAR#33]
Currently, pysarApp.py use subprocess.Popen() to call individual scripts. It should be modified to use pysar as modules to run those steps.  I copied the key points of the discussion below for the reference.

From Falk:
> A problem in PYSAR is that the output from pysarApp.py gets scrambled, which makes debugging very difficult. Check out the functions below. If you run ./test_print_order.py in interactive mode (used by Yunjun for development) you get an output as desired:     

https://github.com/geodesymiami/rsmas_isce/issues/99     

From Josh:
> It’s much explicit and clear to use all of our software as a collection of python modules rather than have a ton of subprocess calls everywhere. Subprocess is not meant to be a substitute to modular software design.    

From Yunjun:
> I would agree that calling them through python module is easy and has more control. But this required each script has a very well organized function to handle all the input arguments. The current pysar code does not have it yet. Thus, calling them through subprocess could use the parsing function on the individual script and does not require rewriting.      

From Josh:
> It would probably be worth it to modify those PySAR scripts that we use in rsmas_insar so they can be called without need to run `subprocess`.

From David:   
> So it looks like I have a really easy fix, since `cmd_line_parse` takes care of arguments really nicely. In the long term, we should move away from putting arguments into a string just to parse them and instead pass in the arguments explicitly.     

> So right now, `pysarApp.py` makes the following subprocess call:    

```
subprocess.Popen(command ="load_data.py --template TemplateFile.txt CustomTemplateFile.txt --project ProjectName", ...)
```

> This can become the following by just leveraging `parser.parse_args` and, voila, we’ve eliminated `subprocess`:    
```
load_data.main("--template TemplateFile.txt CustomTemplateFile.txt --project ProjectName")
```

> However, we should really not rely on `parser.parse_args` at all (for module calls) and make the following call:   

```
load_data.main(template= "TemplateFile.txt",  custom_template= "CustomTemplateFile.txt", project= "ProjectName")
```

> This is how I would do the refactor. However, I would recommend doing the refactor Josh and I just talked about at a later date. I would recommend creating an issue on the matter. https://github.com/yunjunz/PySAR/commit/61ca9c57624ec37ad22f468365aef079f4244e96.

**Comment by yunjunz** [comment]
@2gotgrossman, I agree that refactoring as you and @Ovec8hkin suggested should be the right solution. About calling main() function in the code, do you have any conclusion? Is it a good way to do it, or maybe we should refactor the load_data.py to avoid it?

**Comment by 2gotgrossman** [comment]
I'm semi-neutral on the whole `main()` bit. We should come to a teamwide conclusion, but my recommendation is either `main()` or `run_module_name()`. I'm leaning towards the latter. Also, module names should not be verbs. So `load_data.py` isn't a good module name. Maybe `data_loader`? Then, a call to run the script would be `data_loader.run_data_loader()` or `data_loader.load_data()`

**Comment by 2gotgrossman** [comment]
@yunjunz Are you taking the lead on this refactor?

**Comment by yunjunz** [comment]
@2gotgrossman I can start with `load_data.py` for the refactor. But I don't think I have time for all the other script anytime soon.

**Comment by 2gotgrossman** [comment]
@yunjunz I would start with just refactoring out the `subprocess` calls without modifying the underlying scripts like I did in 61ca9c5

**Comment by yunjunz** [comment]
That would be great @2gotgrossman, I am happy to answer any questions.

**Comment by yunjunz** [comment]
@2gotgrossman, since there will be a lot of module import, maybe we should move the import code inside each function?

**Comment by yunjunz** [comment]
@2gotgrossman I would go for the refactor in pysarApp.py for the subprocess. For your information, I have added a testing script here https://github.com/yunjunz/PySAR/blob/master/test/test_pysarApp.py

**Comment by Ovec8hkin** [comment]
@2gotgrossman I would say the `main()` function for each module should be the actual module name, or something similar. I agree that the module name shouldn't be a verb, so the main function should be the verb form of the module name in that case. So `data_loader.load_data()`, etc.

**Comment by yunjunz** [comment]
@2gotgrossman @Ovec8hkin I hear your point, but I would still prefer `load_data` as the script name because it's clear on what it does and simple.

**Comment by 2gotgrossman** [comment]
> @2gotgrossman, since there will be a lot of module import, maybe we should move the import code inside each function?

@yunjunz I would stick to the pattern of leaving imports at the top of the script. Anything that diverges from that, I would recommend refactoring.

How I would handle this specific case would be to `import pysar` at the top of the module and at each use case, put `pysar.module_name.main()`. For example, 

```pysar.load_data.main(load_data_args)```

**Comment by yunjunz** [comment]
@2gotgrossman perfect!
